name: py

on:
  # schedule:
  #   - cron: "37 1 * * *"    #runs at 15:00 UTC everyday
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        env:
          JOKE_API_KEY: ${{ 'secrets.JOKE_API_KEY' }} # Access secrets
          WEATHER_API_KEY: ${{ 'secrets.WEATHER_API_KEY' }}
          TWILIO_ACCOUNT_SID: ${{ 'secrets.TWILIO_ACCOUNT_SID' }}
          TWILIO_AUTH_TOKEN: ${{ 'secrets.TWILIO_AUTH_TOKEN' }}
        run: |
          python send_sms.py
